[profile.default]
eth_rpc_url = "https://arb1.arbitrum.io/rpc"
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.22"
test = "test/foundry"
src = 'src'
libs = ["lib"]
viaIR=false
match_test = "^test"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@core/=src/core/",
    "@position/=src/position/",
    "@governance/=src/governance/",
    "@constants/=src/constants/",
    "@oracle/=src/oracle/"
]
